const dataString = {
  category: [
    'Alimentation',
    'Cosmétique',
    'Décoration',
    'Habillement',
    'Multimédias et Jouets',
    'Services',
    'Sport',
  ],

  brands: [
    '+2Foot',
    'Alto Café',
    'Amorino',
    'Brasserie Olivium',
    'BUBBLE BAR',
    'Burger Bar by Quick',
    'Camarosa',
    'Columbus Café',
    'Creams Factory',
    'Crêpe Touch',
    'Fresg Factory',
    'Half Time',
    'KFC',
    'Le Club Sandwich',
    'Manhattan’s store',
    'Mezzo Di Pasta',
    "O'Tacos",
    'Papaya Bar',
    'PEPE MANZO',
    'Pitaya',
    'Pomme de Pain',
    'Segafredo',
    'Subway',
    'Sushi Hanaka',
    'Veng Hour',
    'Wok ô King',
    'Yogugrt Factory',
    'Adopt',
    'Bar à S.Cils',
    'Body Minute',
    'Dépil Tech',
    'Franck Provost',
    'Générale d’Optique',
    'Grand Optical',
    "HAIR'minute",
    'Jeff de Bruges',
    'KIKO',
    'La Boutique Du Coiffeur',
    'M-A-C Cosmetics',
    'Marionnaud',
    'Optical Service OS+',
    'Pharmacie',
    'Saint Algue',
    'Sephora',
    'The Body Shop',
    'Twenty Nails',
    'Waffle Factory',
    'Yves Rocher',
    'Action',
    'Flying Tiger Copenhagen',
    'HEMA',
    'MUY MUCHO',
    'Normal',
    'Pylônes',
    'ASICS',
    'Au Masculin',
    'Bershka',
    'Biskuit Paris',
    'Calzedonia',
    'Celio',
    'CHK',
    'CIPO & BAXX',
    'Devred 1902',
    'Easy',
    'Etam Lingerie',
    'Foot Korner',
    'Foot Locker',
    'FORESTLAND',
    'GUESS',
    'H&M',
    'HUNKEMÖLLER',
    'Izac',
    'Jennyfer',
    'Jules',
    'Kaporal',
    'Kiabi',
    'Kombak',
    'Lacoste',
    'Levi’s',
    'Mango',
    'NEW YORKER',
    'OVS Kids',
    'Pimkie Primark',
    'Pull & Bear',
    'Salsa',
    'Sergent Major',
    'Stradivarius',
    "Tape à l'œil",
    'Territoire Redskins',
    'Undiz',
    'X-CLUSIF',
    'ZARA',
    'ZELYS',
    'Bouygues Télécom',
    'Free',
    'GIBERT',
    'Hubside',
    'La Grande Récré',
    'Maxxi Games',
    'Orange',
    'SFR',
    '5àsec',
    'Alter smoke',
    'Cabinet dentaire',
    'COM 9',
    'La Cordonnerie',
    'Photomaton',
    'Promo Vacances',
    'Adidas Originals',
    'BioTech USA',
  ],
};
export default dataString;
